# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-18 04:19
from __future__ import unicode_literals

from django.db import migrations
import separate_users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', separate_users.models.EditorManager()),
            ],
        ),
        migrations.CreateModel(
            name='FrontendUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', separate_users.models.FrontendUserManager()),
            ],
        ),
    ]
